### ISSUE TITLE
Can i use this library for these use cases?

### ISSUE THREAD

**Issue by aloksharma1** [MarkCiliaVincenti/AsyncKeyedLock#10]
hi,

I have some race conditions in my middleware that writes sitemaps for my project and another in IRouteConstraint where i sometimes get exception on double ef calls what's the best way to counter this situation.
I want the middleware to lock file writing request until its finished and make other users to wait for it.

is RabbitMQ queuing ideal for such situations although I think RabbitMQ is overkill hence I am looking for alternative like yours.
what's the best approach here I am stuck between choosing something that won't have a negative impact on project.
there is lot of suggestions on google like semaphore async read write lock etc.

**Comment by MarkCiliaVincenti** [comment]
Do you need to lock by some key though? Because if not (i.e. lock any thread accessing the same resource) you can simply use a normal `SemaphoreSlim` and make sure it's shared between all the threads.

**Comment by aloksharma1** [comment]
@MarkCiliaVincenti well each url is unique for file writing and many groups of users at same time can access that same file for e.g. sitemap-1.txt or sitemap-1.xml so i think yes a key would help?

**Comment by MarkCiliaVincenti** [comment]
So yes you can use this library. Just set the key to whatever you want to deny concurrency access with.
