### ISSUE TITLE
Question: What am I missing here?

### ISSUE THREAD

**Issue by MelGrubb** [MarkCiliaVincenti/AsyncKeyedLock#17]
I'm trying to leverage AsyncKeyedLock to "debounce" some API calls coming from the outside. I want to lock on the Guid Id of the incoming object. The library seems straight-forward, but I wrote a test to try to simulate our situation just to be sure, and I can't get it to act the way I think it should. Here's an isolated test to illustrate what I'm seeing.

```csharp
    [Test]
    public void ParallelVersion()
    {
        var output = new ConcurrentQueue<(int Ordinal, long Start, long Stop)>();
        var stopwatch = Stopwatch.StartNew();

        Parallel.Invoke(
            () => ProcessEntry(Guid.Parse("00000000-0000-0000-0000-000000000000"), 0).Wait(),
            () => ProcessEntry(Guid.Parse("00000000-0000-0000-0000-000000000000"), 2).Wait(),
            () => ProcessEntry(Guid.Parse("00000000-0000-0000-0000-000000000000"), 4).Wait(),
            () => ProcessEntry(Guid.Parse("11111111-1111-1111-1111-111111111111"), 1).Wait(),
            () => ProcessEntry(Guid.Parse("11111111-1111-1111-1111-111111111111"), 3).Wait(),
            () => ProcessEntry(Guid.Parse("11111111-1111-1111-1111-111111111111"), 5).Wait()
        );

        return;

        async Task ProcessEntry(Guid id, int ordinal)
        {
            using (await SUT.LockAsync(id.ToString()))
            {
                var start = stopwatch.ElapsedMilliseconds;
                Console.WriteLine($@"Processing ordinal {ordinal} at {stopwatch.ElapsedMilliseconds}");
                Thread.Sleep(1000);
                var stop = stopwatch.ElapsedMilliseconds;
                output.Enqueue((ordinal, start, stop));
                Console.WriteLine($@"Processed ordinal {ordinal} at {stopwatch.ElapsedMilliseconds}");
            }
        }
    }
```

What I expect to see is that none of the even numbered entries should be processed at the same time, and the same for the odds. I expect one of the evens to start processing, and the other two to wait in line. Meanwhile, one of the odds should also start processing while the other two wait in line. When the first even/odd pair have finished, I would expect another two to get picked up, and so on.

I don't really expect to see them line up 0-5 in the output because Parallel.Invoke isn't going to guarantee order. What I'm seeing in the output queue, though, is that every single entry started processing at the exact same time. It could be that I'm outrunning the library's lock itself, in which case I'm out of luck. The other day we saw two identical calls to our API 2ms apart, so that's the kind of timing I'm trying to guard against. Any guidance would be appreciated.

**Comment by MarkCiliaVincenti** [comment]
Hi,

For completeness sake, can you please include the rest of the class, showing the initialization of SUT?

**Comment by MelGrubb** [comment]
I believe you may have hit on exactly the problem. SUT is created by Moq.Automocker. It's not a mock itself, but any of its dependencies would be, and maybe that's where things are going wrong. The automocker is going to pick the greediest constructor, so it should have settled on the one that takes options, concurrencyLevel, capacity, and a comparer. Since it will have mocked these all out, we can probably assume that at the very least, the mocked comparer is what's throwing it off. Inlining the creation of the locker and taking the default options makes it behave.

Thanks for pointing me in the right direction.

**Comment by MelGrubb** [comment]
I have a follow-up question, though. At runtime, the .Net IoC is also going to try to grab the greediest constructor. I haven't looked at the internals of the .Net IoC, but could this cause similar issues if it picked the wrong one?

**Comment by MarkCiliaVincenti** [comment]
Wouldn't you usually set that up as a singleton via IoC?

**Comment by MelGrubb** [comment]
In the "real world", yes, but the problem I was having was in writing a unit test to document the behavior we're using. Because our tests are using an auto-mocker to create the system under test, and because it always picks the greediest constructor, it was mocking out the comparer, which then threw off the test results. Manually creating the system under test was the fix I needed.
