### ISSUE TITLE
FEAT: Option to await KeyedLock

### ISSUE THREAD

**Issue by MikaelPorttila** [MarkCiliaVincenti/AsyncKeyedLock#57]
Hi,

I'm trying to figure out if this lib handles my use case, I checked the wiki but couldn't really find the option to async await for an existing keyed lock.

My use case is that multiple web requests are done async to fetch resources which are generated on the fly, but I want only the first task to jump on the task on unique keys to create the resource and I create a lock using a file-id/name, and in this case I want all other requests to wait for the first request which grabs the keyed lock to wait for the first thread to complete the task and release the keyed lock.

I found the "IsInUse" function which is the closest to what I search for but it's not enough unless I add lots of extra code to monitor if the result of the function changes, it's not optimal for this specific case.

Are there any other functions in this library which provides this mechanic?

**Example of how these concurrent requests would look like and behave:** 
[Request 1] - > Asks for key "123" -> Locks and process request
[Request 2] -> Asks for key "123" -> Wait until the key "123" is released by [Request 1]
[Request 3] -> Asks for key "345" -> Locks and process request
[Request 4] -> Asks for key "678" -> Locks and process request
... few minutes later when all above requests has completed ...
[Request 5] -> Asks for key "123" -> Only checks for keyed lock **but sets no lock** - no lock detected, grabs cached generated file. 

Thanks in advance! 🚀

**Comment by MarkCiliaVincenti** [comment]
This library is specifically for your use case. Ensure the instance of AsyncKeyedLocker is shared between all threads (static? Singleton DI?) and simply do a using (await keyedLocker.LockAsync(key))

**Comment by MarkCiliaVincenti** [comment]
As for request 5, why not first check whether the file is already created (simple if statement) so it only uses AsyncKeyedLock if the file is not yet created?

**Comment by MikaelPorttila** [comment]
Thank you for the quick reply - much appreciated! :) 

That's how I would typically go about it also but then I started thinking about the initial request on a busy site where multiple concurrent users gets the cache miss and hits the lock, only the first one should do any processing so it would require me to do an extra cache check inside the lock for every operation to really be sure it's not the second thread to process the same key.

A cache check in my case is an I/O-operation to a distributed cache is good to point out and I was hoping that exposing the lock without acquiring a new one would be a cheap way to prevent extra initial requests.

You know the ins and outs of the lib, how hard do you think it would be to expose the lock for a key with the current code base, would it require any major changes or is there an easy way to achieve this without any real side effects on the current features? 

(If you are in doubt about this feature and feel that it doesn't align with your vision for this library I'll make a fork).

**Comment by MarkCiliaVincenti** [comment]
I think you misunderstood me

If (alreadyProcessed(key)) return whatever;

using (await asyncKeyedLocker.LockAsync(key))
{
   If (alreadyProcessed(key)) return whatever;

   ... Create item
}

**Comment by MikaelPorttila** [comment]
The problem with your code example is that your concurrent initial requests with the same key (ex: 123) will get stuck by the LockAsync(key)-part and be processed one at the time and block each other and these will keep on stack up until the initial first thread has managed to create the cache.

Lets say:
- 10 concurrent requests on the same key "123"
- Processing takes 1000ms (We convert an image to WebP on the fly)
- Fetching ```return whatever``` from the distributed cache and resolving etag takes 25ms

Would result in:
- The first request would take 1000ms bacause it takes on the task of the heavy processing.
- The last request would take 1000ms + 9*25 ms = 1225 ms due to the queue created by the write-lock and the 9 other concurrent requests which missed the cache.

By adding a lock-wait which doesn't set a lock check around the first ``` alreadyProcessed(key) ```, all those request would hit the cache simultaneously once the first thread release the keyed lock and the rest of the requests would take max 1025 ms.

I hope you see the scaling issue here and what I'm trying to solve

**Comment by MarkCiliaVincenti** [comment]
What about this? Do you have a lot of keys? Can alreadyProcessed check a HashSet?

If (alreadyProcessed(key)) return processedItem;

using (await asyncKeyedLocker.LockAsync(key))
{
If (!alreadyProcessed(key)) createItem(key);
}

return processedItem;

**Comment by MikaelPorttila** [comment]
Introducing another threadsafe-collection to keep track of keys might help but it would need to keep track if the cache has already been checked already otherwise extra I/O-request will be done anyway.

My original idea was to keep it simple by "just waiting" (not knowing how hard it would be to add such API in your library) for an already existing keyed-lock from memory without extra complexity in the calling project.

Not sure if you see the same potential as me with this feature, there might be more use cases for a reader-lock-awaiter, i'm not gonna stress more about it, but I see no harm in having such option the toolset of this library. 

Please close the issue if you don't see any future for this feature in your library and I thank you for this discussion and your time!

**Comment by MarkCiliaVincenti** [comment]
If I understand you correctly you want something similar to this library but rather than being based on Semaphoreslim it would be based on Manualreseteventslim. But that would be half the problem since you'd still not want to reprocess if it's already been done. This is quite a specific use case.

Why not use a ConcurrentDictionary of Manualreseteventslim and never cleaning up after use? If you've added you force other threads to wait. Once processed you signal for all other threads to proceed. Any thread that comes after finds it in the dictionary and can proceed through the Manualreseteventslim

**Comment by MarkCiliaVincenti** [comment]
Did this answer your query?
