### ISSUE TITLE
Enable deterministic build

### ISSUE THREAD

**Issue by MagicAndre1981** [MarkCiliaVincenti/AsyncKeyedLock#8]
Add [DotNet.ReproducibleBuilds](https://github.com/dotnet/reproducible-builds#dotnetreproduciblebuilds-nuget-package) to make [deterministic builds](https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/):

> Deterministic builds ensure that the same binary is produced regardless of the machine building it, including paths to sources stored in the symbols.

With this package all settings are enabled, PDBs and sourcelink infos are embedded into the DLL. With this you can step into source code without cloning the repo and using a self compiled DLL.

**Comment by MarkCiliaVincenti** [comment]
I will look into the implications of this.

As cons I see adding a dependency for everyone, larger package sizes and I'm not sure if there's any effect at all on performance (do you?)

The pros need to outweigh the cons. Why are you stepping into the source code, do you have an actual problem?

**Comment by MarkCiliaVincenti** [comment]
I've stumbled upon this, would this work for you?
https://github.com/dotnet/sourcelink

**Comment by MagicAndre1981** [comment]
This is implicitly added via [DotNet.ReproducibleBuilds](https://github.com/dotnet/reproducible-builds#dotnetreproduciblebuilds-nuget-package). And DotNet.ReproducibleBuilds is a [developer dependency (see the PrivateAssets entry of PackageReference Include](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets) only for you, the user has no additional dependencies:

`<PackageReference Include="DotNet.ReproducibleBuilds" Version="1.1.1" PrivateAssets="All"/>`

You only have pros like able to step into code, only small con is a little larger package size as the PDB data with the sourcelink JSON are embedded in the DLL.

**Comment by MarkCiliaVincenti** [comment]
Will performance be affected in any way?

**Comment by MarkCiliaVincenti** [comment]
Are you interested in creating a PR for this so I could create a pre-release version and benchmark performance?

**Comment by MagicAndre1981** [comment]
Done with #9 :

File size of package is only a bit larger

![image](https://user-images.githubusercontent.com/8274816/215100935-5debe2be-d114-47cd-bc4f-c87c74bc8ff5.png)

And when you turn off "Just my code" in VS debug options and try to step into you need to accept the warning

![_download_file_vs_debug](https://user-images.githubusercontent.com/8274816/215103675-6c51f21e-f2c9-483d-a3c8-53a177c7f0bc.png)

you can step into the code magically 

![_download_file_vs_debug_2](https://user-images.githubusercontent.com/8274816/215103825-33f92482-d8dc-42bc-848d-0fe561bf65c1.png)

**Comment by MarkCiliaVincenti** [comment]
Brilliant, thank you!

I released 6.1.1-beta and it's currently being benchmarked against 6.1.0 at https://github.com/MarkCiliaVincenti/AsyncKeyedLockBenchmarks/actions/runs/4025314083/jobs/6918371621
